/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_frmFoablak (void)
{
  GtkWidget *frmFoablak;
  GtkWidget *vbox1;
  GtkWidget *lblFoablak;
  GtkWidget *hbox1;
  GtkWidget *btn1;
  GtkWidget *btn2;
  GtkWidget *btn3;
  GtkWidget *hbox2;
  GtkWidget *btnOpen;
  GtkWidget *btnAbout;
  GtkWidget *btnExit;

  frmFoablak = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (frmFoablak), _("Foablak (lookup)"));
  gtk_window_set_default_size (GTK_WINDOW (frmFoablak), 500, 400);

  vbox1 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (frmFoablak), vbox1);

  lblFoablak = gtk_label_new (_("Ez is valtozni fog"));
  /***/
  //bar nem szep, de itt is csinalunk egy hozzarendelest a foablak es a foablak cimkeje kozott, hogy kesobb is el tudjuk erni (foablak --> foablak cimkeje):
  gtk_object_set_data (GTK_OBJECT(frmFoablak), "fo-cimke", lblFoablak);
  /***/
  gtk_widget_show (lblFoablak);
  gtk_box_pack_start (GTK_BOX (vbox1), lblFoablak, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lblFoablak), GTK_JUSTIFY_LEFT);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  btn1 = gtk_button_new_with_mnemonic (_("1"));
  gtk_widget_show (btn1);
  gtk_box_pack_start (GTK_BOX (hbox1), btn1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (btn1), 5);
  gtk_button_set_relief (GTK_BUTTON (btn1), GTK_RELIEF_NONE);

  btn2 = gtk_button_new_with_mnemonic (_("2"));
  gtk_widget_show (btn2);
  gtk_box_pack_start (GTK_BOX (hbox1), btn2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (btn2), 5);
  gtk_button_set_relief (GTK_BUTTON (btn2), GTK_RELIEF_NONE);

  btn3 = gtk_button_new_with_mnemonic (_("3"));
  gtk_widget_show (btn3);
  gtk_box_pack_start (GTK_BOX (hbox1), btn3, TRUE, TRUE, 0);
  gtk_button_set_relief (GTK_BUTTON (btn3), GTK_RELIEF_NONE);

  hbox2 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, TRUE, TRUE, 0);

  btnOpen = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (btnOpen);
  gtk_box_pack_start (GTK_BOX (hbox2), btnOpen, TRUE, TRUE, 0);

  btnAbout = gtk_button_new_from_stock ("gnome-stock-about");
  gtk_widget_show (btnAbout);
  gtk_box_pack_start (GTK_BOX (hbox2), btnAbout, TRUE, TRUE, 0);

  btnExit = gtk_button_new_from_stock ("gtk-quit");
  gtk_widget_show (btnExit);
  gtk_box_pack_start (GTK_BOX (hbox2), btnExit, TRUE, TRUE, 0);

  g_signal_connect ((gpointer) btn1, "clicked",
                    G_CALLBACK (on_btn1_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn2, "clicked",
                    G_CALLBACK (on_btn2_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn3, "clicked",
                    G_CALLBACK (on_btn3_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnOpen, "clicked",
                    G_CALLBACK (on_btnOpen_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnAbout, "clicked",
                    G_CALLBACK (on_btnAbout_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnExit, "clicked",
                    G_CALLBACK (on_btnExit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (frmFoablak, frmFoablak, "frmFoablak");
  GLADE_HOOKUP_OBJECT (frmFoablak, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (frmFoablak, lblFoablak, "lblFoablak");
  GLADE_HOOKUP_OBJECT (frmFoablak, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (frmFoablak, btn1, "btn1");
  GLADE_HOOKUP_OBJECT (frmFoablak, btn2, "btn2");
  GLADE_HOOKUP_OBJECT (frmFoablak, btn3, "btn3");
  GLADE_HOOKUP_OBJECT (frmFoablak, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (frmFoablak, btnOpen, "btnOpen");
  GLADE_HOOKUP_OBJECT (frmFoablak, btnAbout, "btnAbout");
  GLADE_HOOKUP_OBJECT (frmFoablak, btnExit, "btnExit");

  return frmFoablak;
}

GtkWidget*
create_frmMellekablak (void)
{
  GtkWidget *frmMellekablak;
  GtkWidget *vbox2;
  GtkWidget *lblMellekablak;
  GtkWidget *hbox3;
  GtkWidget *btnA;
  GtkWidget *btnB;
  GtkWidget *btnC;
  GtkWidget *btnClose;

  frmMellekablak = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (frmMellekablak), _("Mellekablak (lookup)"));

  vbox2 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (frmMellekablak), vbox2);

  lblMellekablak = gtk_label_new (_("Ez is valtozni fog..."));
  /***/
  //bar nem szep, de itt is csinalunk egy hozzarendelest a mellekablak es a mellekablak cimkeje kozott, hogy kesobb is el tudjuk erni (mellekablak --> mellekablak cimkeje):
  gtk_object_set_data (GTK_OBJECT(frmMellekablak), "mellek-cimke", lblMellekablak);
  /***/
  gtk_widget_show (lblMellekablak);
  gtk_box_pack_start (GTK_BOX (vbox2), lblMellekablak, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (lblMellekablak), GTK_JUSTIFY_LEFT);

  hbox3 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox3, TRUE, TRUE, 0);

  btnA = gtk_button_new_with_mnemonic (_("A"));
  gtk_widget_show (btnA);
  gtk_box_pack_start (GTK_BOX (hbox3), btnA, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (btnA), 5);

  btnB = gtk_button_new_with_mnemonic (_("B"));
  gtk_widget_show (btnB);
  gtk_box_pack_start (GTK_BOX (hbox3), btnB, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (btnB), 5);

  btnC = gtk_button_new_with_mnemonic (_("C"));
  gtk_widget_show (btnC);
  gtk_box_pack_start (GTK_BOX (hbox3), btnC, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (btnC), 5);

  btnClose = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (btnClose);
  gtk_box_pack_start (GTK_BOX (vbox2), btnClose, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (btnClose), 20);

  g_signal_connect ((gpointer) btnA, "clicked",
                    G_CALLBACK (on_btnA_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnB, "clicked",
                    G_CALLBACK (on_btnB_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnC, "clicked",
                    G_CALLBACK (on_btnC_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnClose, "clicked",
                    G_CALLBACK (on_btnClose_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (frmMellekablak, frmMellekablak, "frmMellekablak");
  GLADE_HOOKUP_OBJECT (frmMellekablak, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (frmMellekablak, lblMellekablak, "lblMellekablak");
  GLADE_HOOKUP_OBJECT (frmMellekablak, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (frmMellekablak, btnA, "btnA");
  GLADE_HOOKUP_OBJECT (frmMellekablak, btnB, "btnB");
  GLADE_HOOKUP_OBJECT (frmMellekablak, btnC, "btnC");
  GLADE_HOOKUP_OBJECT (frmMellekablak, btnClose, "btnClose");

  return frmMellekablak;
}

GtkWidget*
create_frmAbout (void)
{
  const gchar *authors[] = {
    "The NeverGone :)",
    NULL
  };
  const gchar *documenters[] = { NULL };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator_credits");
  GtkWidget *frmAbout;

  if (!strcmp (translators, "translator_credits"))
    translators = NULL;
  frmAbout = gnome_about_new ("lookup", VERSION,
                        _("GPL"),
                        "",
                        authors,
                        documenters,
                        translators,
                        NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (frmAbout, frmAbout, "frmAbout");

  return frmAbout;
}
