/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *frmFoablak, *frmMellekablak;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gnome_program_init (PACKAGE, VERSION, LIBGNOMEUI_MODULE,
                      argc, argv,
                      GNOME_PARAM_APP_DATADIR, PACKAGE_DATA_DIR,
                      NULL);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  frmFoablak = create_frmFoablak ();
  //letrehozza a segedablakot:
  frmMellekablak = create_frmMellekablak ();
  //beallitja a hozzarendelest a foablak es a mellekablak kozott "masodik_ablak" neven (foablak --> mellekablak):
  gtk_object_set_data (GTK_OBJECT(frmFoablak), "masodik_ablak", frmMellekablak);
  //beallitja a hozzarendelest mellekablak es a foablak kozott "elso_ablak" neven (mellekablak --> foablak):
  gtk_object_set_data (GTK_OBJECT(frmMellekablak), "elso_ablak", frmFoablak);
 gtk_widget_show (frmFoablak);

  gtk_main ();
  return 0;
}
