/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *frmFoablak, *frmMellekablak;

/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  frmFoablak = create_frmFoablak ();
  //letrehozza a segedablakot:
  frmMellekablak = create_frmMellekablak ();
  //beallitja a hozzarendelest a foablak es a mellekablak kozott "masodik_ablak" neven (foablak --> mellekablak):
  gtk_object_set_data (GTK_OBJECT(frmFoablak), "masodik_ablak", frmMellekablak);
  //beallitja a hozzarendelest mellekablak es a foablak kozott "elso_ablak" neven (mellekablak --> foablak):
  gtk_object_set_data (GTK_OBJECT(frmMellekablak), "elso_ablak", frmFoablak);
 gtk_widget_show (frmFoablak);

  gtk_main ();
  return 0;
}
